# Generated by Django 4.1.4 on 2022-12-07 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("homeNo", models.CharField(max_length=10)),
                ("post", models.CharField(max_length=30)),
                ("dist", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=10)),
                ("pin", models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("age", models.IntegerField(max_length=3)),
                ("sex", models.CharField(max_length=2)),
                ("color", models.CharField(max_length=30)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="New_API.address",
                    ),
                ),
            ],
        ),
    ]
