# Generated by Django 4.1.4 on 2022-12-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("New_API", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address", name="pin", field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="person", name="age", field=models.IntegerField(),
        ),
    ]
